blank_issues_enabled: false
contact_links:
  - name: TheHive Community Support
    url: https://chat.thehive-project.org/
    about: Please ask and answer questions here.
  - name: TheHive Documentation
    url: https://docs.strangebee.com/
    about: Please read documentation here.
